server:
  port: 9011
spring:
  application:
    name: gateway
  redis:
    database: 0
    host: 20.0.0.106
    jedis:
      pool:
        max-active: 10
eureka:
  client:
    service-url:
      defaultZone: http://localhost:9010/eureka/
feign:
  hystrix:
    enabled: true
zuul:
  host:
    connect-timeout-millis: 60000
    socket-timeout-millis: 60000
  prefix: /api
  routes:
    #路由名称，随意，唯一即可(表示只要HTTP请求是 /grp开始的，就会forward到服务id为group_server的服务上面)
    group:
        #路由的路径
        path: /grp/**
        #服务名称
        serviceId: group-server
    user:
      path: /usr/**
      serviceId: user-server